{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "lamp.fullname" . }}-app
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 0
spec:
  tls:
  - secretName: {{ template "lamp.fullname" . }}-tls-app
    hosts:
    - {{ template "lamp.domain" . }}
  rules:
  - host: {{ template "lamp.domain" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "lamp.fullname" . }}
          servicePort: {{ .Values.service.HTTPPort }}
{{- end }}
