.catalog:
  name: OsNxP7Mdb
  version: 0.1
  description: "Odiseasoft Template Nginx Php7 MariaDB"
  uuid: OsNxP7Mdb-0
  questions:
    - variable: public_port
      description: "public port to access the WordPress site"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"
